services:
  app-dev:
    container_name: linx_ui_dev
    build:
      context: .
      target: base
      args:
        NODE_ENV: development
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev -- --host
networks:
  linx_network:
    external: true
